@startuml
title GenderRatios
center header Pokémon | Domain Model
'''''''''''''
'''''''''''''

object Genderless{
    PercentageToBeMale = 0%
    PercentageToBeFemale = 0%
    --
    (RatioFemaleMale = 0♀ : 0♂)
}

object MaleOnly{
    PercentageToBeMale = 100%
    PercentageToBeFemale = 0%
    --
    (RatioFemaleMale = 0♀ : 1♂)
}

object MostlyMale{
    PercentageToBeMale = 87.5%
    PercentageToBeFemale = 12.5%
    --
    (RatioFemaleMale = 1♀ : 7♂)
}

object UsuallyMale{
    PercentageToBeMale = 75%
    PercentageToBeFemale = 25%
    --
    (RatioFemaleMale = 1♀ : 3♂)
}

object Balanced{
    PercentageToBeMale = 50%
    PercentageToBeFemale = 50%
    --
    (RatioFemaleMale = 1♀ : 1♂)
}

object UsuallyFemale{
    PercentageToBeMale = 25%
    PercentageToBeFemale = 75%
    --
    (RatioFemaleMale = 3♀ : 1♂)
}

object MostlyFemale{
    IsGenderLess = false
    --
    PercentageToBeMale = 12.5%
    PercentageToBeFemale = 87.5%
    --
    (RatioFemaleMale = 7♀ : 1♂)
}

object FemaleOnly{
    PercentageToBeMale = 0%
    PercentageToBeFemale = 100%
    --
    (RatioFemaleMale = 1♀ : 0♂)
}

'''''''''''''

Balanced .d. Genderless #transparent

MaleOnly .u. MostlyMale #transparent
MostlyMale .r. UsuallyMale #transparent
UsuallyMale .r. Balanced #transparent

FemaleOnly .u. MostlyFemale #transparent
MostlyFemale .l. UsuallyFemale #transparent
UsuallyFemale .l. Balanced #transparent

'''''''''''''
'''''''''''''
right footer (CC-BY) RGV, 2021
@enduml