@startuml
'https://plantuml.com/object-diagram
title Basics, 2020 Edition
center header Squid Game
'''''''''''''

object Contest
object 2020

object Games
object Players

object Winner{
number = 456
name = Seong Gi-hun
}

object EliminatedPlayers{
numbers = [1,455]
}

object Prize{
quantity = 46B ₩
}

object AddingPrize{
quantity = 100M ₩ each
}

object Participants

object Game1{
Red Light, Green Light
}
object Game2{
Sugar Honeycombs
}
object Game3{
Tug of War
}
object Game4{
Marbles
}
object Game5{
Hopscotch
}
object Game6{
Squid Game
}
Game2 .l. Game1 #transparent
Game3 .l. Game2 #transparent
Game4 .l. Game3 #transparent
Game5 .l. Game4 #transparent
Game6 .l. Game5 #transparent

'''''''''''''


Contest *- 2020
Contest *-- "456" Players
Contest *-- "6" Games

Winner -u-|> Players
EliminatedPlayers -u-|> Players

EliminatedPlayers -- AddingPrize
AddingPrize --> "+" Prize

Winner .. "doesn't use :)" Prize

Players .. Participants

Game1 --u-|> Games
Game2 --u-|> Games
Game3 --u-|> Games
Game4 --u-|> Games
Game5 --u-|> Games
Game6 --u-|> Games

Game1 *-- Participants : 456
Game2 *-- Participants : 201
Game3 *-- Participants : 80
Game4 *-- Participants : 32
Game5 *-- Participants : 16
Game6 *-- Participants : 2

'''''''''''''
right footer (CC-BY) RGV, 2021
@enduml
